version: '3'

services:

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: drupal:8-apache
    networks:
      - skynet
    ports:
      - 8080:80
    restart: always
    volumes:
      - .:/var/www/html

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    environment:
      MYSQL_DATABASE: default
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: default
    image: mysql:5.7
    networks:
      - skynet
    restart: always
    volumes:
      - ~/.docker-data/drupal8/mysql:/var/lib/mysql

networks:
  skynet:
    driver: "bridge"
